### ISSUE TITLE
P-curve returns negative estimates

### ISSUE THREAD

**Issue by Joe-Hilgard** [nicebread/meta-showdown#3]
As of November 6th, p-curve seems to have a mysterious long tail, sometimes estimating effects as very negative (d = -1 or more) even when delta = 0.8 and there are no QRPs. The problem seems to attenuate with increasing effect size and sample size.

Perhaps a test could be written that halts the run when the p-curve estimate is very small, such that the data and estimating process could be examined.

**Comment by evanccarter** [comment]
The current plan is to examine how the p-curve estimate varies as a function of the number of studies included in the analysis. This seems like a plausible next step given the pattern of negative bias (i.e., reducing with higher sample and effect sizes).

**Comment by yostx038** [comment]
very negative estimates are produced by p-curve when the submitted studies have many high (.045) p-values and very few or no low (.01) p-values.

quick example:

> t = c(2.10, 2.105, 2.11, 2.117)
> df = c(32, 32, 32, 32)
> pcurveEst(t = t, df = df)
> Bootstrapping [=======================================================================================================================] 100% ETA:  0s
>   method variable     value
> 1 pcurve        d -1.936439
> 2 pcurve       lb -1.936491
> 3 pcurve       ub -1.695140
> 
> t = c(2.10, 2.105, 2.11, 3.117)
> df = c(32, 32, 32, 32)
> pcurveEst(t = t, df = df)
> Bootstrapping [=======================================================================================================================] 100% ETA:  0s
>   method variable      value
> 1 pcurve        d -1.5910814
> 2 pcurve       lb -1.9364911
> 3 pcurve       ub  0.7826454
> 
> t = c(2.10, 2.105, 3.11, 3.117)
> df = c(32, 32, 32, 32)
> pcurveEst(t = t, df = df)
> Bootstrapping [=======================================================================================================================] 100% ETA:  0s
>   method variable      value
> 1 pcurve        d  0.1783123
> 2 pcurve       lb -1.8531661
> 3 pcurve       ub  0.9496694
>

**Comment by evanccarter** [comment]
Interesting. That jibes with my previous comment, since you're more likely to get a set with that kind of profile when you're looking at smaller samples.

**Comment by Joe-Hilgard** [comment]
I took Yost's example p-values and threw them into the p-curve app. The app, notably, does not report an effect size or a CI -- when things look badly p-hacked, it simply demurs by saying that "Power < 5%".

![image](https://cloud.githubusercontent.com/assets/6798949/11223587/bb5a970e-8d3e-11e5-977d-c42be04d6c35.png)
It also outputs a plot of the Kolmogorov-Smirnov D-stat at each level of estimated power. You can see that in the badly-hacked scenario the line is both flat and high, indicating that p-curve has some awareness that its effect size estimate (and hence, power estimate) is not right.

Maybe what we're seeing are odd cases where, even with 10--20 studies, delta = 0.8, and no QRPs, p-curve still only catches just one or two p > .025.

It's inelegant, but maybe an appropriate kludge would be to floor such an estimate at d = 0? No human being would look at a left-skewed p-curve and say "Aha, the true effect is actually in the opposite direction!" Instead, they'd say "I suspect there's no effect here."

![image](https://cloud.githubusercontent.com/assets/6798949/11223975/a83b3082-8d40-11e5-9c98-36dcfcc4b63b.png)
You can see that the R script considers d < 0 whereas the p-curve app does not seem to. You can also see that the KS d-stat becomes degenerate and that the minimum is still bad.

In this light, maybe our code and/or data generation isn't wrong, but a floor of 0 would make for an appropriate kludge. Thoughts?

**Comment by wgervais** [comment]
Not a bad idea, Joe.

Also, can we record that "goodness of fit" for each meta? Seems nice that
it doesn't just shoot out an estimate, but also gives info about how
reasonable the estimate is likely to be.

W

**Comment by yostx038** [comment]
> Maybe what we're seeing are odd cases where, even with 10--20 studies, delta = 0.8, and no QRPs, p-curve still only catches just one or two p > .025.
> 
> That would be my guess as well. Esp. when bootstrapping with few studies, oddball combinations like the one I emailed earlier will happen often enough to produce that long tail.
> 
> It's inelegant, but maybe an appropriate kludge would be to floor such an estimate at d = 0? No human being would look at a left-skewed p-curve and say "Aha, the true effect is actually in the opposite direction!" Instead, they'd say "I suspect there's no effect here.”

I suggest that we simply leave it be and not floor it at d = 0, and simply let p-curve do its thing. If p-curve doesn’t work in some cases or produces weird output, that’s not our fault - we’re only trying to assess how well p-curve works compared to PET, PEESE etc. It is possible to produce left-skewed p-curves when testing real effects..

**Comment by Joe-Hilgard** [comment]
> I suggest that we simply leave it be and not floor it at d = 0, and simply let p-curve do its thing. If p-curve doesn’t work in some cases or produces weird output, that’s not our fault - we’re only trying to assess how well p-curve works compared to PET, PEESE etc. It is possible to produce left-skewed p-curves when testing real effects..

I'm not sure I agree. If we're interested in the mean squared error of each statistic as it's interpreted, then leaving the big negative estimates in there is going to very unfairly punish _p_-curve's mean squared error.

Maybe we can add some value to the _p_-curve method by mentioning the caveat -- effect size estimates < 0 should be floored at zero. It seems kinda wasteful to me not to correct the problem and move on.

That said, I can also see the case for mentioning that, once in a blue moon, you might see somebody unfairly accused of p-hacking because of a "lucky bounce" test, e.g. two studies each at _p_ = .045. Of course, if there are no null results reported besides the two _p_ = .045, then publication bias is extremely likely. But we might want to soften the conclusions in light of the potential harms of "trial by _p_-value."

I wonder if the same problem ever happens in PET, too... My meta-analysis suggested _r_ = -.12 for one outcome, mostly because of one extreme outlier that was probably a reporting error. Again, I think these techniques are generally used for comparing delta = 0 against one tail, so I don't think we should could d < 0 against them.

**Comment by nicebread** [comment]
> > I suggest that we simply leave it be and not floor it at d = 0, and 
> > simply let p-curve do its thing. If p-curve doesn’t work in some 
> > cases or produces weird output, that’s not our fault - we’re only 
> > trying to assess how well p-curve works compared to PET, PEESE etc. 
> > It is possible to produce left-skewed p-curves when testing real 
> > effects..
> 
> I'm not sure I agree. If we're interested in the mean squared error of 
> each statistic as it's interpreted, then leaving the big negative 
> estimates in there is going to very unfairly punish _p_-curve's mean 
> squared error.

What about making two p-curves:
- the naive p-curve (with the punishment)
- an enhanced p-curve (which we have to figure out - e.g., "only use if 
  > 5 sig. studies & goodness of fit < X; else estimate = 0)

But that would go beyond the original scope - then we could also think 
about an "enhanced PET-PEESE" etc.

F

**Comment by evanccarter** [comment]
I agree. I'm reluctant to fix p-curve here. I think we should just do a
good job cataloguing what's going on with it (and the other methods,
assuming we find a variety of weaknesses). 'Here's the MSE, etc., and those
stats are what they are because of the following issues.' Then we can make
a general suggestion based on the points that have been raised so far. I
think this project is already quite large and is going to be a little
difficult to a PoPS audience as is.

Evan C. Carter
Postdoctoral Research Associate
Department of Neuroscience
University of Minnesota

**Comment by wgervais** [comment]
Hey gang,

How about we report whatever pcurve spits out, but also record its goodness of fit estimate?

I'm guessing most of the wonky pcurve estimates would be flagged by pcurve as having terrible fit (one would hope).

This way we include the bug (weird values) alongside the potential feature (it might be able to tell you when to ignore it). Win-win. We could also track correlations between fit and estimate accuracy.

W

Words by Will. Typos by iPhone

**Comment by nicebread** [comment]
But what actually is the fit measure of p-curve? The loss function? But 
that probably also depends on the number of p-values, etc.?

F

**Comment by evanccarter** [comment]
Just sent an email with plots. If someone wants to code it up to spit out
the loss function fit I could easily replace sig.studies in the emailed
plots. I agree with Felix, though, they're likely very correlated. Someone
want to do a quick sim on that? The relation between fit and number of
studies included in the p-curve?

Evan C. Carter
Postdoctoral Research Associate
Department of Neuroscience
University of Minnesota

**Comment by wgervais** [comment]
Yeah, it probably is related to number of studies. But it could be useful
to look at.

Incidentally, this is probably something shared by all the methods (not
worth a lick without sufficient data...holds for regression, p-curve, etc).
But if p-curve will give us something quantifiable in that regard, it seems
silly to me to not include it. More data = yay!

W

---

Will Gervais
Assistant Professor
University of Kentucky Psychology
www.willgervais.com

**Comment by Joe-Hilgard** [comment]
Just to keep the record in the GitHub issue thread as well as email...

Again, I think we should focus on how will these techniques will be interpreted and used --- as one-sided tests. 

A left-skewed _p_-curve suggests _p_-hacking, but it does not imply a large, negative, true effect. Nobody would claim that hot water actually makes you lonelier.

Again, I've seen PET also return negative estimates because of outliers. It's clear in these cases that the reasonable estimate is zero.

(Comically, trim-and-fill never seems to suffer from this problem because it is garbage at recovering the null hypothesis.)

> But what actually is the fit measure of p-curve? The loss function? 

Yes, as best I understand it. It's the Kolmogorov-Smirnov test's d-stat, reflecting the misfit between the observed QQ plot and the hypothesized QQ plot based on the _p_-curve estimate. (I think. I'm not great at KS test.)

> an enhanced p-curve (which we have to figure out - e.g., "only use if
>  5 sig. studies & goodness of fit < X; else estimate = 0)
> How about we report whatever pcurve spits out, but also record its goodness of fit estimate?

Again, I think the simplest solution is just to say that a left-skewed _p_-curve (e.g. d =< 0, power < 5%) means that all bets are off. Spares us having to worry about complex rules or trying to establish a cutoff for d-stat.
