### ISSUE TITLE
summ$method has deprecated (?) level "fill"

### ISSUE THREAD

**Issue by Joe-Hilgard** [nicebread/meta-showdown#4]
In summ.RData, there are 432 rows associated with summ$method == "fill". These rows have missing data for columns meanEst:consisZero.D. Perhaps this was originally the label for the trim-and-fill method and is now deprecated?

**Comment by evanccarter** [comment]
This, I believe, is for the number of studies filled in by the
trim-and-fill. The trim-and-fill estimate should be under TF.

Evan C. Carter
Postdoctoral Research Associate
Department of Neuroscience
University of Minnesota
