### ISSUE TITLE
MSE may not be calculating properly in summ.RData

### ISSUE THREAD

**Issue by Joe-Hilgard** [nicebread/meta-showdown#6]
Column `summ$MSE` seems to simply be the square of column `summ$ME`. That's a problem: we'd expect at least some degree of bias/variance tradeoff.

In any case, the MSE values seem implausibly small. Even if we accept that PET is unbiased when delta = 0, tau = 0, one would still expect variance because PET does not hit exactly 0 every time. Similarly, increasing _k_ should decrease MSE, but it does not.

Test this with:
`summary(summ$ME - (summ$MSE)^2)`
Observe that all differences are within rounding error.

**Comment by nicebread** [comment]
Right, there was an error in the code: mean(d - meanD.sig, na.rm=TRUE)^2
Should be mean((d - meanD.sig)^2, na.rm=TRUE). Fixed it & commited new summ.RData

I also fixed the factor labels.
