### ISSUE TITLE
Don't reject H0 if adjusted estimate is negative

### ISSUE THREAD

**Issue by Joe-Hilgard** [nicebread/meta-showdown#7]
I'm concerned our Type 1 error rates are higher than they should be because sometimes the estimator overcorrects, yielding a significant effect of opposite sign.

To eliminate this possibility, I would like to change how H0 is rejected so that *p* must be less than .05 and the effect must be of the anticipated positive sign.

https://github.com/nicebread/meta-showdown/blob/master/5-hypTest.R#L26
`res.hyp$H0.reject <- (res.hyp$p.value < res.hyp$p.crit) & (res.hyp$b0_estimate > 0)`

I'd make the change myself but I don't have res.wide.red so I can't make sure that I'm not breaking the code. Felix?

**Comment by wgervais** [comment]
Good catch!

**Comment by Joe-Hilgard** [comment]
I was wondering also if PET-PEESE needs a similar fix, but I decided against it. This fix should handle all relevant cases for the purpose of rejection ratio. I'm recording my thoughts here for posterity.

I was thinking, sometimes when the funnel is asymmetrical and a high-precision study is nonsignificant or on the low side of heterogeneity, PET will return a significant negative effect, e.g.

`PETPEESE.est(c(3, 2, 1, -.5), c(1, .5, .25, .1))`

will return a PET.lm estimate of *d* = -2.2, *p* = .033, and so PET-PEESE will return the PEESE estimate, *d* = -0.7, *p* = .237.

In these cases we're probably not at risk of falsely rejecting H0 because PEESE tends to bring the wildly negative PET estimate back towards 0. But it may be something to keep in mind, especially if we're gonna use the PET-PEESE significance test for the hybrid 3PP procedure.

**Comment by nicebread** [comment]
Done - H0.rejection now uses only positive estimates. Significantly negative estimates are counted as "do not reject H0".
