### ISSUE TITLE
an ME.pos and RMSE.pos could also be useful

### ISSUE THREAD

**Issue by Joe-Hilgard** [nicebread/meta-showdown#8]
We should consider what our recommendation to treat d < 0 as d ~ 0 will do to bias and efficiency, therefore...

https://github.com/nicebread/meta-showdown/blob/master/3-resultsFramework.R#L86

Propose adding lines
`ME.pos 			= mean(posify(b0_estimate) - delta, na.rm=TRUE),`
`RMSE.pos		= sqrt(mean((posify(b0_estimate) - delta)^2, na.rm=TRUE)),`

I'd do it myself but I don't have enough RAM to run 3_resultsFramework.R.

**Comment by nicebread** [comment]
Added and committed summary files.
