### ISSUE TITLE
P-Curve ES estimate optimisation

### ISSUE THREAD

**Issue by ARawles** [nicebread/meta-showdown#9]
I've noticed that in the presence of many highly significant results, the optimisation function in P-Curve.R;

 `out[1, 1] <- optim(par=0, fn=pcurve_loss, pc_data = pc_data, method="BFGS")$par`

returns very small effect size estimates as opposed to very large effect size estimates. I'm fairly sure this is because the gradient of the optimisation graph at small effect size estimates is so close to 0, the function returns those values rather than finding the true lowest value of the curve.

For the moment, I've found that;

 `out[1,1] <- optimize(pcurve_loss,interval = c(0, max(pc_data$d_vals)), pc_data = pc_data)$minimum`

avoids this problem.

**Comment by nicebread** [comment]
Thanks for the note, good catch! As observed by McShane et al (2016), the loss function used for p-curve is inefficient anyway (compared to ML), but otherwise equivalent. In practice it maybe makes sense to simply use the equivalent 1PSM model based on ML estimation. The erratic behavior you observed might be related to a figure in van Aert et al. (2016).

**Comment by ARawles** [comment]
The problem only really reared its head at true effect sizes of 0.9 and above so it's not a huge issue.

Myself and Richard Morey are investigating that hypothesis - that an ML estimation may provide more efficient ES estimations - using simulations, which is when we ran into this problem!

I'll be sure to revisit that Van Aert paper. Can you remember which figure?

**Comment by nicebread** [comment]
It's van Aert, R. C. M., Wicherts, J. M., & van Assen, M. A. L. M. (2016). Conducting Meta-Analyses Based on pValues. Perspectives on Psychological Science, 11(5), 713–729. http://doi.org/10.1177/1745691616650874, Figure 2: 
<img width="479" alt="grafik" src="https://user-images.githubusercontent.com/2391270/28824323-c10e0d34-76c1-11e7-8ecc-eb771ce9c1d6.png">

Excellent that you investigate the ML estimation! I am really looking forward to your results.
